### ISSUE TITLE
first attempt at contribution

### ISSUE THREAD

**Issue by adrem1** [cardano-foundation/stake-pool-school-handbook#1]
Hi all,

I hope this finds you well. Thank you for making the SPS a public repository! I will admit to being quite novice to github, so I'll add my contributions here as issues, until I figure out the whole pull-request thing. 

As seen in the forum thread here: https://forum.cardano.org/t/updating-the-stake-pool-school/43303 I would like to modify parts of the code to reflect changes in the software versions, as follows:

**Page visited 11.01.2021**: https://cardano-foundation.gitbook.io/stake-pool-course/stake-pool-guide/getting-started/install-node

**Information to be revised:**
The below sections aim to 1) download and install GHC, 2) find the latest release of cardano-node and tag it and 3) copy the newly compiled binaries to the appropriate directory.

#1_____________________________________________________________
wget https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-deb9-linux.tar.xz
tar -xf ghc-8.6.5-x86_64-deb9-linux.tar.xz
rm ghc-8.6.5-x86_64-deb9-linux.tar.xz
cd ghc-8.6.5
./configure
sudo make install
cd …

#2_____________________________________________________________
git fetch --all --tags
git tag
git checkout tags/1.19.1

#3_____________________________________________________________
cp -p dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-node-1.19.1/x/cardano-node/build/cardano-node/cardano-node ~/.local/bin/

cp -p dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-cli-1.19.1/x/cardano-cli/build/cardano-cli/cardano-cli ~/.local/bin/

**Suggested revisions:**
At the time of writing the software versions are GHC 8.10.2 and cardano-node 1.24.2. The code should be revised, and kept up to date to reflect this:

#1_____________________________________________________________
wget https://downloads.haskell.org/~ghc/8.10.2/ghc-8.10.2-x86_64-deb9-linux.tar.xz
tar -xf ghc-8.10.2-x86_64-deb9-linux.tar.xz
rm ghc-8.10.2-x86_64-deb9-linux.tar.xz
cd ghc-8.10.2
./configure
sudo make install

#2_____________________________________________________________
git fetch --all --tags
git tag
git checkout tags/1.24.2

#3_____________________________________________________________
cp -p dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-node-1.24.2/x/cardano-node/build/cardano-node/cardano-node ~/.local/bin/

cp -p dist-newstyle/build/x86_64-linux/ghc-8.10.2/cardano-cli-1.24.2/x/cardano-cli/build/cardano-cli/cardano-cli ~/.local/bin/

Please let me know if this is not the type/style of contribution you are after. I am happy to try and modify thigs directly here, I just need to learn how. 

Cheers,

A

**Comment by adrem1** [comment]
Figured out the Pull Request thing, al least I think I have :)

**Comment by katomm** [comment]
@adrem1 Yes, you have to fork the stake pool repo, then connect the newly created repo on your GitHub with gitbook.io (so that you can try out the changes and everything)

Afterwards you can create a pull request with your changes back to the repo of the Cardano Foundation.
