### ISSUE TITLE
SPS still focussed exclusively on testnet?

### ISSUE THREAD

**Issue by adrem1** [cardano-foundation/stake-pool-school-handbook#19]
As the title says, I wonder if the book should also provide for those that want to have a go directly on mainnet? 

I personally was too concerned about my abilities to do this, but I have heard many budding SPOs keen to do it this way, by having for example a "private" pool to begin with (eg 100% fees to keep delegators away). 

While working on Testnet (which for me was a great way to iron out my own doubts), one of the issues that kept popping up with other operators was that there was little scope to asses ROA performance, as the funds available through faucet were too scarce to simulate a block-minting pool. At the time I didn't think it was a great concern, but some others did and found it very frustrating. I don't know if this is still the case and I will endeavour to do more research and look back at material I have not opened for a while. 

What is the opinion of people about this?

Cheers,

A

**Comment by rdlrt** [comment]
It is very important that folks dont try things on mainnet (as majority end up incorrectly using the guides to learn linux as well). As such I like that recommendation in general should always stick for SPOs to learn and get comfortable on Testnet first.

**Comment by katomm** [comment]
I totally agree with @rdlrt here. The entire school should be in the testnets. This knowledge should not be acquired in the mainnet.

What would certainly be good at one point to explain how to proceed when you feel confident enough.

We could make a page/chapter for resources like the Guild Operators, Cardano Forum and other a few other sites that deal extensively with the SPO subject.

**Comment by adrem1** [comment]
To you both, thank you for the feedback. Great to have a common direction,
for this and other projects/guides.

Cheers,

A
