### ISSUE TITLE
GHC install instructions forget about CentOS/RHEL systems

### ISSUE THREAD

**Issue by greerben0** [cardano-foundation/stake-pool-school-handbook#24]
https://cardano-foundation.gitbook.io/stake-pool-course/stake-pool-guide/getting-started/install-node#download-and-install-ghc

Suggest updating to include wget and other commands for CentOS/RHEL systems. 
```
wget https://downloads.haskell.org/~ghc/8.10.2/ghc-8.10.2-x86_64-centos7-linux.tar.xz
tar -xf ghc-8.10.2-x86_64-centos7-linux.tar.xz
rm ghc-8.10.2-x86_64-centos7-linux.tar.xz
```

**Comment by rdlrt** [comment]
Its resolved as per the mentioned PR, OK to close?
