### ISSUE TITLE
Example UTxO query uses allegra-era for shelley testnet

### ISSUE THREAD

**Issue by greerben0** [cardano-foundation/stake-pool-school-handbook#31]
https://github.com/cardano-foundation/stake-pool-school-handbook/blob/master/stake-pool-guide/stake-pool-operations/keys_and_addresses.md

Copy-paste of example results in an error `Shelley command failed: query utxo  Error: A query from a certain era was applied to a ledger from a different era: EraMismatch {ledgerEraName = "Shelley", otherEraName = "Allegra"}`.

Recommend example command uses `--shelley-era` flag or nothing because that appears to be the default era

**Comment by rdlrt** [comment]
@greerben0 - Make sure your node is in sync. `--shelley-era` is not valid after allegra fork.
